version: "3"

services:
  pystonk:
    image: pystonk:latest
    container_name: pystonk
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    entrypoint:
      - /bin/bash
      - docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - "./pystonk:/opt/app/pystonk"
      - "./tests:/opt/app/tests"
  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    env_file:
      - .env
    command: [ "http", "host.docker.internal:3000" ]