version: "3"

services:
  pystonk:
    image: pystonk:latest
    container_name: pystonk
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    entrypoint:
      - /bin/bash
      - docker/entrypoint.sh
    volumes:
      - ".:/opt/app"